### ISSUE TITLE
firmware zte mc801a T-mobile Germany

### ISSUE THREAD

**Issue by proudturk** [stich86/ZTE-MC7010#1]
Hello. can you update your tool to work with zte mc801a ?

**Comment by stich86** [comment]
Hi,

this repo is just for informations. The EDL tool from @bkerler already support MC801A/A1. Just use correct loader (the one for 7010 can also works)

So what your issue?

**Comment by proudturk** [comment]
Hi,

I have a mc801a router. The T-Mobile software in Germany is blocked and the router is out of service. I installed some firmware for mc801a but the device does not turn on. The device only turns on with 801a1 firmware but no service. I think there is a problem with nv-ram or efs folder. If there is a software that allows the device to work like a phone, can you share it if possible?

Thank you,

**Comment by proudturk** [comment]
Hi,

I have a mc801a router. The T-Mobile software in Germany is blocked and the router is out of service. I installed some firmware for mc801a but the device does not turn on. The device only turns on with 801a1 firmware but no service. I think there is a problem with nv-ram or efs folder. If there is a software that allows the device to work like a phone, can you share it if possible?

Thank you,

**Comment by stich86** [comment]
T-Mobile 801A is "particular" (Like 801A1 H3G UK or 801A1 for EAST MARKET) and needs it's original firmware or alternative one

write me an email to stich86@hack-gpon.org, we can get in touch and I can help you to restore your router :)

**Comment by proudturk** [comment]
thank you, I wrote an email.
